language: node_js
node_js:
  - "stable"
services:
  - postgresql
cache:
  directories:
  - app/node_modules
  - server/node_modules
  - node_modules
before_script:
  - psql -c 'create database barkingo;' -U postgres
  - psql -c 'CREATE TABLE users (id character varying(150) PRIMARY KEY, name character varying(150) NOT NULL, email character varying(150) NOT NULL UNIQUE, password character varying(150), googletoken character varying(200), facebooktoken character varying(200));' -U postgres
  - touch server/creds.json
  - echo '{"db":{"user":"postgres","host":"localhost","database":"barkingo","password":"","port":5432},"secret":"superimportantaixonses"}' >> creds.json
  - cd app
  - npm i
  - cd ..
  - cd server
  - npm i
  - cd ..
  - npm i -g create-react-app
script:
  - npm test
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: dev
dist: trusty
